# Resource allocation
general_mem_gb: 60
general_threads: 3
general_time_hr: 40

# Input samples
input_transcript_abundance_matrix: "/mnt/isilon/xing_lab/aspera/xuy/IRIS-long_SCLC_test/test_abun.txt"
input_transcript_gtf: "/mnt/isilon/xing_lab/aspera/xuy/IRIS-long_SCLC_test/test.gtf"
tumor_key_word: "SCLC"
outf_dir: "/mnt/isilon/xing_lab/aspera/xuy/IRIS-long_SCLC_test/test_out"

# Genome fasta and gtf will be downloaded automatically if missing
genome_version: "hg38"
gencode_release_version: "46"
genome_fasta_path:
genome_fasta_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/GRCh38.primary_assembly.genome.fa.gz"
genome_gtf_path:
genome_gtf_url: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.annotation.gtf.gz"

# Parameters in pre-processing:
normalized_mode: 'SELF'

# Parameters in differential transcript identification
num_tumor_sample: 10
enriched_test_p_value: 0.05
enriched_test_cpm_in_tumor: 5
enriched_test_fc: 2
specificity_test_cpm_in_tumor: 5
specificity_test_cpm_in_tissue: 1
specificity_test_minimum_percentage_in_tumor: 0.5
specificity_test_maximal_percentage_in_tissue: 0.1
specificity_test_exclude_tissue: "Testis"

# Parameters in transcript translation:
mode: "long-read"

# Parameters in TCR prediction:
HLA_str_inf: "/mnt/isilon/xing_lab/aspera/xuy/IRIS-long_SCLC/SCLC_HLA.txt"
AA_window_size: 11
binding_affi: 500
minimum_specificity_score_TCR: 5
maximal_peptide_cpm_in_tissue_TCR: 5
maximal_tissue_percentage_TCR: 0.1

# Parameters in CAR-T prediction:
minimum_specificity_score_CAR_T: 3
maximal_peptide_cpm_in_tissue_CAR_T: 10
maximal_tissue_percentage_CAR_T: 0.1

# Parameters in figure generation:
group_info_inf: "group_info.txt"
required_trans_inf: "required_trans.txt"

# Additional configuration
IRIS_long_path: "/mnt/isilon/xing_lab/aspera/xuy/Test/IRIS_long_2/"
tmhmm_dir: "/mnt/isilon/xing_lab/aspera/xuy/tmhmm-2.0c/bin/"
netMHCpan_dir: "/home/xuy2/xuy2/program/netMHCpan-4.1/"
conda_wrapper: '/mnt/isilon/xing_lab/aspera/xuy/Test/conda_wrapper'

